baseURL = "https://maklem.eu/"
locale = 'de'
title = 'maklem.eu'

[module]
    [[module.imports]]
        disable = false
        ignoreConfig = false
        ignoreImports = false
        path = 'github.com/nunocoracao/blowfish/v2'

[menus]
[[menus.main]]
name = "Blog"
pageRef = "blog"
weight = 10

[[menus.main]]
name = "Linktree"
pageRef = "linktree"
weight = 20

[params]
colorScheme = "avocado"