baseURL = "https://maklem.eu/"
locale = 'de'
title = 'maklem.eu'

[module]
    [[module.imports]]
        disable = false
        ignoreConfig = false
        ignoreImports = false
        path = 'github.com/nunocoracao/blowfish/v2'

[menus]
[[menus.main]]
name = "Blog"
pageRef = "blog"
weight = 10

[[menus.main]]
parent = "Blog"
name = "Alle Artikel"
pageRef = "blog"
weight = 10

[[menus.main]]
parent = "Blog"
name = "Kategorien"
pageRef = "categories"
weight = 15

[[menus.main]]
parent = "Blog"
name = "Tags"
pageRef = "tags"
weight = 20


[[menus.main]]
name = "Linktree"
pageRef = "linktree"
weight = 30

[params]
colorScheme = "avocado"
enableSearch = false
homepage.layout = "background"
homepage.showRecent = true
homepage.showRecentItems = 1
defaultFeaturedImage = "/img/feature_3.png"
defaultBackgroundImage = "/img/background.jpg"

[params.header]
layout = "fixed"

[params.list]
showHero = true
heroStyle = "background"
showTaxonomies = true
showSummary = true

[params.article]
showHero = true
heroStyle = "background"
showAuthorBottom = true
showTaxonomies = true

[params.author]
name = "Dr. Marco Klement"
headline = "Projektmitarbeiter FDM @ FAU"
subtitle = "Softwareentwicklung, Serverpflege"
bio = "Projektmitarbeiter Forschungsdatenmanagement @ FAU"
links = [
#    { rss = "https://maklem.eu/index.xml" },
    { email = "hallo-von-maklem-eu-website@leuchtstark.dev" },
    { pgpkey = "https://leuchtstark.dev/.well-known/openpgpkey/hu/y73za89mt8f3axdnxbbkuxkxec6qqtri" },
    { matrix = "https://matrix.to/#/@maklem:leuchtstark.dev" },
    { github = "https://github.com/maklem" },
    { fediverse = "https://social.leuchtstark.dev/@maklem" },
    { image = "https://social.leuchtstark.dev/@maklem_photography" },
#    { codeberg = "https://codeberg.org/maklem/" },
#    { bluesky = "https://bsky.app/profile/leuchtstark.dev" },
#    { linkedin = "https://www.linkedin.com/in/marco-klement/" },
#    { orcid = "https://orcid.org/0000-0001-9958-7291" },
#    { xing = "https://www.xing.com/profile/Marco_Klement034256" },
]

[taxonomies]
  category = 'categories'
  tag = 'tags'